---
# locale: en_US
session:
  # save_handler: internal/files
  # save_path: /tmp/session
  # name: gini-session
  cookie:
    lifetime: 0
    path: /
    domain: ~
    secure: false
    httponly: false
  autostart: true
timezone: Asia/Shanghai
postmaster:
  address: support@geneegroup.com
  name: Genee
log:
  ident: gini
  option: 5
  facility: 8
rurl_mod:
  js:
    query: '_v=$(VERSION)'
  css:
    query: '_v=$(VERSION)'
...
